"""combine problempulse migrations

Revision ID: 03c23269e5d4
Revises: 
Create Date: 2026-04-25 17:14:05.326388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03c23269e5d4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('session_token', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('admin', 'super_admin', name='adminrole'), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('selected_features', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_id'), 'feedback', ['id'], unique=False)
    op.create_table('otp_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('otp', sa.String(), nullable=False),
    sa.Column('reset_token', sa.String(), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_records_email'), 'otp_records', ['email'], unique=False)
    op.create_index(op.f('ix_otp_records_id'), 'otp_records', ['id'], unique=False)
    op.create_table('prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('billed', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prices_id'), 'prices', ['id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_index(op.f('ix_teams_slug'), 'teams', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firebase_uid', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_onboarded', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_id'), 'contact', ['id'], unique=False)
    op.create_table('onboarding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('discovery', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('usage', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('occupation', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_onboarding_id'), 'onboarding', ['id'], unique=False)
    op.create_table('packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('monthly_price_id', sa.Integer(), nullable=True),
    sa.Column('annual_price_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['annual_price_id'], ['prices.id'], ),
    sa.ForeignKeyConstraint(['monthly_price_id'], ['prices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packages_id'), 'packages', ['id'], unique=False)
    op.create_table('playstore_queries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.Text(), nullable=False),
    sa.Column('app_id', sa.Text(), nullable=False),
    sa.Column('app_name', sa.Text(), nullable=True),
    sa.Column('runpod_job_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('failed_at_step', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summarized_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playstore_queries_id'), 'playstore_queries', ['id'], unique=False)
    op.create_index(op.f('ix_playstore_queries_status'), 'playstore_queries', ['status'], unique=False)
    op.create_index(op.f('ix_playstore_queries_user_email'), 'playstore_queries', ['user_email'], unique=False)
    op.create_index(op.f('ix_playstore_queries_user_id'), 'playstore_queries', ['user_id'], unique=False)
    op.create_table('reddit_queries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.Text(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('clarification_count', sa.Integer(), nullable=False),
    sa.Column('conversation_history', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('search_queries', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('runpod_job_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('failed_at_step', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('clarified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('searched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summarized_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reddit_queries_id'), 'reddit_queries', ['id'], unique=False)
    op.create_index(op.f('ix_reddit_queries_status'), 'reddit_queries', ['status'], unique=False)
    op.create_index(op.f('ix_reddit_queries_user_email'), 'reddit_queries', ['user_email'], unique=False)
    op.create_index(op.f('ix_reddit_queries_user_id'), 'reddit_queries', ['user_id'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_progress', 'closed', name='ticketstatus'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', name='ticketpriority'), nullable=False),
    sa.Column('ticket_type', sa.Enum('login_issue', 'ai_performance', 'payment', 'search_results', 'feature_request', 'billing', 'account', 'other', name='tickettype'), nullable=False),
    sa.Column('user_plan', sa.Enum('free', 'starter', 'pro', name='userplan'), nullable=False),
    sa.Column('assigned_team', sa.String(length=50), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_id'), 'tickets', ['id'], unique=False)
    op.create_index(op.f('ix_tickets_ticket_id'), 'tickets', ['ticket_id'], unique=True)
    op.create_table('user_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_action', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_activity_id'), 'user_activity', ['id'], unique=False)
    op.create_index(op.f('ix_user_activity_user_id'), 'user_activity', ['user_id'], unique=True)
    op.create_table('user_activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('action_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_user_activity_log_user_date')
    )
    op.create_index(op.f('ix_user_activity_log_id'), 'user_activity_log', ['id'], unique=False)
    op.create_index(op.f('ix_user_activity_log_user_id'), 'user_activity_log', ['user_id'], unique=False)
    op.create_table('user_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan', sa.String(), nullable=False),
    sa.Column('credits_total', sa.Integer(), nullable=False),
    sa.Column('credits_used', sa.Integer(), nullable=True),
    sa.Column('purchased_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_query_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_plans_id'), 'user_plans', ['id'], unique=False)
    op.create_table('playstore_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query_id', sa.UUID(), nullable=False),
    sa.Column('app_id', sa.Text(), nullable=False),
    sa.Column('review_id', sa.String(length=255), nullable=True),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('thumbs_up', sa.Integer(), nullable=True),
    sa.Column('review_created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reply_content', sa.Text(), nullable=True),
    sa.Column('reply_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['playstore_queries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('query_id', 'review_id', name='uq_playstore_review_query_review')
    )
    op.create_index(op.f('ix_playstore_reviews_app_id'), 'playstore_reviews', ['app_id'], unique=False)
    op.create_index(op.f('ix_playstore_reviews_id'), 'playstore_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_playstore_reviews_query_id'), 'playstore_reviews', ['query_id'], unique=False)
    op.create_table('playstore_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query_id', sa.UUID(), nullable=False),
    sa.Column('app_id', sa.Text(), nullable=False),
    sa.Column('app_name', sa.Text(), nullable=True),
    sa.Column('analyzed_at', sa.Text(), nullable=True),
    sa.Column('direct_answer', sa.Text(), nullable=True),
    sa.Column('executive_summary', sa.Text(), nullable=True),
    sa.Column('overall_sentiment', sa.Text(), nullable=True),
    sa.Column('total_signals', sa.Integer(), nullable=True),
    sa.Column('average_rating', sa.Text(), nullable=True),
    sa.Column('themes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('market_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actionable_next_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rating_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['playstore_queries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playstore_summaries_id'), 'playstore_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_playstore_summaries_query_id'), 'playstore_summaries', ['query_id'], unique=True)
    op.create_table('reddit_posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query_id', sa.UUID(), nullable=False),
    sa.Column('search_query', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('doc_id', sa.String(length=255), nullable=True),
    sa.Column('reddit_id', sa.String(length=255), nullable=True),
    sa.Column('reddit_title', sa.Text(), nullable=True),
    sa.Column('reddit_selftext', sa.Text(), nullable=True),
    sa.Column('reddit_author', sa.String(length=255), nullable=True),
    sa.Column('reddit_subreddit_id', sa.String(length=255), nullable=True),
    sa.Column('reddit_subreddit', sa.String(length=255), nullable=True),
    sa.Column('reddit_score', sa.Integer(), nullable=True),
    sa.Column('reddit_num_comments', sa.Integer(), nullable=True),
    sa.Column('reddit_created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reddit_url', sa.Text(), nullable=True),
    sa.Column('reddit_fetch_ok', sa.Boolean(), nullable=True),
    sa.Column('reddit_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reddit_comments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_approved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['reddit_queries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('query_id', 'url', name='uq_reddit_post_query_url')
    )
    op.create_index(op.f('ix_reddit_posts_id'), 'reddit_posts', ['id'], unique=False)
    op.create_index(op.f('ix_reddit_posts_query_id'), 'reddit_posts', ['query_id'], unique=False)
    op.create_index(op.f('ix_reddit_posts_url'), 'reddit_posts', ['url'], unique=False)
    op.create_table('reddit_query_contexts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query_id', sa.UUID(), nullable=False),
    sa.Column('user_query', sa.Text(), nullable=True),
    sa.Column('queries', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('nlp_anchors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('topic_boundary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('schema_hints', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['reddit_queries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reddit_query_contexts_id'), 'reddit_query_contexts', ['id'], unique=False)
    op.create_index(op.f('ix_reddit_query_contexts_query_id'), 'reddit_query_contexts', ['query_id'], unique=False)
    op.create_table('reddit_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query_id', sa.UUID(), nullable=False),
    sa.Column('search_query', sa.Text(), nullable=False),
    sa.Column('subreddit', sa.Text(), nullable=True),
    sa.Column('analyzed_at', sa.Text(), nullable=True),
    sa.Column('direct_answer', sa.Text(), nullable=True),
    sa.Column('executive_summary', sa.Text(), nullable=True),
    sa.Column('overall_sentiment', sa.Text(), nullable=True),
    sa.Column('total_signals', sa.Integer(), nullable=True),
    sa.Column('themes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('market_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actionable_next_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['reddit_queries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reddit_summaries_id'), 'reddit_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_reddit_summaries_query_id'), 'reddit_summaries', ['query_id'], unique=True)
    op.create_table('ticket_replies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_admin', sa.Integer(), nullable=True),
    sa.Column('reply_type', sa.String(length=20), nullable=False),
    sa.Column('forwarded_from_team', sa.String(length=50), nullable=True),
    sa.Column('forwarded_to_team', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_replies_id'), 'ticket_replies', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_replies_id'), table_name='ticket_replies')
    op.drop_table('ticket_replies')
    op.drop_index(op.f('ix_reddit_summaries_query_id'), table_name='reddit_summaries')
    op.drop_index(op.f('ix_reddit_summaries_id'), table_name='reddit_summaries')
    op.drop_table('reddit_summaries')
    op.drop_index(op.f('ix_reddit_query_contexts_query_id'), table_name='reddit_query_contexts')
    op.drop_index(op.f('ix_reddit_query_contexts_id'), table_name='reddit_query_contexts')
    op.drop_table('reddit_query_contexts')
    op.drop_index(op.f('ix_reddit_posts_url'), table_name='reddit_posts')
    op.drop_index(op.f('ix_reddit_posts_query_id'), table_name='reddit_posts')
    op.drop_index(op.f('ix_reddit_posts_id'), table_name='reddit_posts')
    op.drop_table('reddit_posts')
    op.drop_index(op.f('ix_playstore_summaries_query_id'), table_name='playstore_summaries')
    op.drop_index(op.f('ix_playstore_summaries_id'), table_name='playstore_summaries')
    op.drop_table('playstore_summaries')
    op.drop_index(op.f('ix_playstore_reviews_query_id'), table_name='playstore_reviews')
    op.drop_index(op.f('ix_playstore_reviews_id'), table_name='playstore_reviews')
    op.drop_index(op.f('ix_playstore_reviews_app_id'), table_name='playstore_reviews')
    op.drop_table('playstore_reviews')
    op.drop_index(op.f('ix_user_plans_id'), table_name='user_plans')
    op.drop_table('user_plans')
    op.drop_index(op.f('ix_user_activity_log_user_id'), table_name='user_activity_log')
    op.drop_index(op.f('ix_user_activity_log_id'), table_name='user_activity_log')
    op.drop_table('user_activity_log')
    op.drop_index(op.f('ix_user_activity_user_id'), table_name='user_activity')
    op.drop_index(op.f('ix_user_activity_id'), table_name='user_activity')
    op.drop_table('user_activity')
    op.drop_index(op.f('ix_tickets_ticket_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_reddit_queries_user_id'), table_name='reddit_queries')
    op.drop_index(op.f('ix_reddit_queries_user_email'), table_name='reddit_queries')
    op.drop_index(op.f('ix_reddit_queries_status'), table_name='reddit_queries')
    op.drop_index(op.f('ix_reddit_queries_id'), table_name='reddit_queries')
    op.drop_table('reddit_queries')
    op.drop_index(op.f('ix_playstore_queries_user_id'), table_name='playstore_queries')
    op.drop_index(op.f('ix_playstore_queries_user_email'), table_name='playstore_queries')
    op.drop_index(op.f('ix_playstore_queries_status'), table_name='playstore_queries')
    op.drop_index(op.f('ix_playstore_queries_id'), table_name='playstore_queries')
    op.drop_table('playstore_queries')
    op.drop_index(op.f('ix_packages_id'), table_name='packages')
    op.drop_table('packages')
    op.drop_index(op.f('ix_onboarding_id'), table_name='onboarding')
    op.drop_table('onboarding')
    op.drop_index(op.f('ix_contact_id'), table_name='contact')
    op.drop_table('contact')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_teams_slug'), table_name='teams')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_prices_id'), table_name='prices')
    op.drop_table('prices')
    op.drop_index(op.f('ix_otp_records_id'), table_name='otp_records')
    op.drop_index(op.f('ix_otp_records_email'), table_name='otp_records')
    op.drop_table('otp_records')
    op.drop_index(op.f('ix_feedback_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
