"""update validate market source model

Revision ID: 0e721a1fb45f
Revises: a9bd98a7512f
Create Date: 2026-09-23 15:18:16.461880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e721a1fb45f'
down_revision: Union[str, Sequence[str], None] = 'a9bd98a7512f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('validate_market_sources', 'snippet')
    op.drop_column('validate_market_sources', 'fetch_ok')
    op.drop_column('validate_market_sources', 'fetched_at')
    op.drop_column('validate_market_sources', 'source_content')
    op.drop_column('validate_market_sources', 'user_approved')
    op.drop_column('validate_market_sources', 'source_title')
    op.drop_column('validate_market_sources', 'source_author')
    op.drop_column('validate_market_sources', 'doc_id')
    op.drop_column('validate_market_sources', 'source_metadata')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('validate_market_sources', sa.Column('source_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('validate_market_sources', sa.Column('doc_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('validate_market_sources', sa.Column('source_author', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('validate_market_sources', sa.Column('source_title', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('validate_market_sources', sa.Column('user_approved', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('validate_market_sources', sa.Column('source_content', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('validate_market_sources', sa.Column('fetched_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('validate_market_sources', sa.Column('fetch_ok', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('validate_market_sources', sa.Column('snippet', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
