"""add onboarding table

Revision ID: 1a61915ae104
Revises: 3f673b92abca
Create Date: 2026-03-25 13:04:30.114084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a61915ae104'
down_revision: Union[str, Sequence[str], None] = '3f673b92abca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboarding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('discovery', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('usage', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('occupation', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_onboarding_id'), 'onboarding', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_onboarding_id'), table_name='onboarding')
    op.drop_table('onboarding')
    # ### end Alembic commands ###
