"""ai lead engine

Revision ID: 30ef420646ce
Revises: 42fe1e572d18
Create Date: 2026-04-30 14:03:47.935033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = '30ef420646ce'
down_revision: Union[str, Sequence[str], None] = '42fe1e572d18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('intent', sa.String(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('service_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('service_embedding_text', sa.Text(), nullable=True),
    sa.Column('buyer_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('buyer_embedding_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_id'), 'campaigns', ['id'], unique=False)
    op.create_index(op.f('ix_campaigns_last_synced_at'), 'campaigns', ['last_synced_at'], unique=False)
    op.create_index(op.f('ix_campaigns_user_id'), 'campaigns', ['user_id'], unique=False)
    op.create_table('campaign_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('changed_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('runpod_job_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_history_campaign_id'), 'campaign_history', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_history_id'), 'campaign_history', ['id'], unique=False)
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(), nullable=False),
    sa.Column('match_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keywords_campaign_id'), 'keywords', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_keywords_id'), 'keywords', ['id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('campaign_history_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('search_keyword', sa.String(), nullable=False),
    sa.Column('ai_score', sa.Integer(), nullable=True),
    sa.Column('vector_score', sa.Float(), nullable=True),
    sa.Column('intent', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('budget_signal', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('feedback', sa.String(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('embedding_text', sa.Text(), nullable=True),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('embedded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_history_id'], ['campaign_history.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_campaign_history_id'), 'leads', ['campaign_history_id'], unique=False)
    op.create_index(op.f('ix_leads_campaign_id'), 'leads', ['campaign_id'], unique=False)
    op.create_index('ix_leads_embedding_hnsw', 'leads', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_table('lead_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('reply_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_actions_id'), 'lead_actions', ['id'], unique=False)
    op.create_index(op.f('ix_lead_actions_lead_id'), 'lead_actions', ['lead_id'], unique=False)
    op.create_table('lead_posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.Column('post_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subreddit_id', sa.String(length=255), nullable=True),
    sa.Column('subreddit', sa.String(length=255), nullable=True),
    sa.Column('reddit_comments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fetch_ok', sa.Boolean(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_posts_id'), 'lead_posts', ['id'], unique=False)
    op.create_index(op.f('ix_lead_posts_lead_id'), 'lead_posts', ['lead_id'], unique=False)
    op.drop_table('feedbacks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedbacks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('feedback_text', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('feedbacks_pkey'))
    )
    op.drop_index(op.f('ix_lead_posts_lead_id'), table_name='lead_posts')
    op.drop_index(op.f('ix_lead_posts_id'), table_name='lead_posts')
    op.drop_table('lead_posts')
    op.drop_index(op.f('ix_lead_actions_lead_id'), table_name='lead_actions')
    op.drop_index(op.f('ix_lead_actions_id'), table_name='lead_actions')
    op.drop_table('lead_actions')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_index('ix_leads_embedding_hnsw', table_name='leads', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_leads_campaign_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_campaign_history_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_keywords_id'), table_name='keywords')
    op.drop_index(op.f('ix_keywords_campaign_id'), table_name='keywords')
    op.drop_table('keywords')
    op.drop_index(op.f('ix_campaign_history_id'), table_name='campaign_history')
    op.drop_index(op.f('ix_campaign_history_campaign_id'), table_name='campaign_history')
    op.drop_table('campaign_history')
    op.drop_index(op.f('ix_campaigns_user_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_last_synced_at'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_id'), table_name='campaigns')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
