"""support and package

Revision ID: 42fe1e572d18
Revises: 03c23269e5d4
Create Date: 2026-04-27 16:33:53.969829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42fe1e572d18'
down_revision: Union[str, Sequence[str], None] = '03c23269e5d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('otp_hash', sa.String(), nullable=True))
    op.add_column('admins', sa.Column('otp_expiry', sa.DateTime(), nullable=True))
    op.add_column('admins', sa.Column('otp_attempts', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('admins', sa.Column('reset_token', sa.String(), nullable=True))
    op.add_column('admins', sa.Column('reset_token_expiry', sa.DateTime(), nullable=True))
    op.add_column('packages', sa.Column('package_type', sa.String(), nullable=False, server_default='Free'))
    op.add_column('packages', sa.Column('is_free', sa.Boolean(), nullable=False, server_default='True'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('packages', 'is_free')
    op.drop_column('packages', 'package_type')
    op.drop_column('admins', 'reset_token_expiry')
    op.drop_column('admins', 'reset_token')
    op.drop_column('admins', 'otp_attempts')
    op.drop_column('admins', 'otp_expiry')
    op.drop_column('admins', 'otp_hash')
    # ### end Alembic commands ###
