"""add all the models for validate idea

Revision ID: 5ae54a2f3203
Revises: 689e76e581df
Create Date: 2026-09-16 15:49:20.473470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ae54a2f3203'
down_revision: Union[str, Sequence[str], None] = '689e76e581df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validate_market_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query_id', sa.UUID(), nullable=False),
    sa.Column('search_query', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('doc_id', sa.String(length=255), nullable=True),
    sa.Column('source_title', sa.Text(), nullable=True),
    sa.Column('source_content', sa.Text(), nullable=True),
    sa.Column('source_author', sa.String(length=255), nullable=True),
    sa.Column('source_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fetch_ok', sa.Boolean(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_approved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['validate_queries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('query_id', 'url', name='uq_validate_market_source_query_url')
    )
    op.create_index(op.f('ix_validate_market_sources_id'), 'validate_market_sources', ['id'], unique=False)
    op.create_index(op.f('ix_validate_market_sources_query_id'), 'validate_market_sources', ['query_id'], unique=False)
    op.create_index(op.f('ix_validate_market_sources_url'), 'validate_market_sources', ['url'], unique=False)
    op.create_table('validate_query_contexts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query_id', sa.UUID(), nullable=False),
    sa.Column('market_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('nlp_anchors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('topic_boundary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('schema_hints', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['validate_queries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validate_query_contexts_id'), 'validate_query_contexts', ['id'], unique=False)
    op.create_index(op.f('ix_validate_query_contexts_query_id'), 'validate_query_contexts', ['query_id'], unique=False)
    op.create_table('validate_score_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query_id', sa.UUID(), nullable=False),
    sa.Column('search_query', sa.Text(), nullable=False),
    sa.Column('analyzed_at', sa.Text(), nullable=True),
    sa.Column('direct_answer', sa.Text(), nullable=True),
    sa.Column('executive_summary', sa.Text(), nullable=True),
    sa.Column('overall_sentiment', sa.Text(), nullable=True),
    sa.Column('total_signals', sa.Integer(), nullable=True),
    sa.Column('quantitative_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('defensibility_vectors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actionable_next_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['validate_queries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validate_score_summaries_id'), 'validate_score_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_validate_score_summaries_query_id'), 'validate_score_summaries', ['query_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validate_score_summaries_query_id'), table_name='validate_score_summaries')
    op.drop_index(op.f('ix_validate_score_summaries_id'), table_name='validate_score_summaries')
    op.drop_table('validate_score_summaries')
    op.drop_index(op.f('ix_validate_query_contexts_query_id'), table_name='validate_query_contexts')
    op.drop_index(op.f('ix_validate_query_contexts_id'), table_name='validate_query_contexts')
    op.drop_table('validate_query_contexts')
    op.drop_index(op.f('ix_validate_market_sources_url'), table_name='validate_market_sources')
    op.drop_index(op.f('ix_validate_market_sources_query_id'), table_name='validate_market_sources')
    op.drop_index(op.f('ix_validate_market_sources_id'), table_name='validate_market_sources')
    op.drop_table('validate_market_sources')
    # ### end Alembic commands ###
