"""added all sources column in validate summary model

Revision ID: 5bad5956763c
Revises: 0e721a1fb45f
Create Date: 2026-09-23 17:57:13.370518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5bad5956763c'
down_revision: Union[str, Sequence[str], None] = '0e721a1fb45f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('validate_score_summaries', sa.Column('all_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('validate_score_summaries', 'all_sources')
    # ### end Alembic commands ###
