"""add RedditQuery, RedditQueryContext, RedditPost, RedditSummary table

Revision ID: 64ab69aa9f06
Revises: 1a61915ae104
Create Date: 2026-03-25 16:43:25.849531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '64ab69aa9f06'
down_revision: Union[str, Sequence[str], None] = '1a61915ae104'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reddit_queries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.Text(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('clarification_count', sa.Integer(), nullable=False),
    sa.Column('conversation_history', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('search_queries', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('runpod_job_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('failed_at_step', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('clarified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('searched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summarized_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reddit_queries_id'), 'reddit_queries', ['id'], unique=False)
    op.create_index(op.f('ix_reddit_queries_status'), 'reddit_queries', ['status'], unique=False)
    op.create_index(op.f('ix_reddit_queries_user_email'), 'reddit_queries', ['user_email'], unique=False)
    op.create_index(op.f('ix_reddit_queries_user_id'), 'reddit_queries', ['user_id'], unique=False)
    op.create_table('reddit_posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query_id', sa.UUID(), nullable=False),
    sa.Column('search_query', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('doc_id', sa.String(length=255), nullable=True),
    sa.Column('reddit_id', sa.String(length=255), nullable=True),
    sa.Column('reddit_title', sa.Text(), nullable=True),
    sa.Column('reddit_selftext', sa.Text(), nullable=True),
    sa.Column('reddit_author', sa.String(length=255), nullable=True),
    sa.Column('reddit_subreddit_id', sa.String(length=255), nullable=True),
    sa.Column('reddit_subreddit', sa.String(length=255), nullable=True),
    sa.Column('reddit_score', sa.Integer(), nullable=True),
    sa.Column('reddit_num_comments', sa.Integer(), nullable=True),
    sa.Column('reddit_created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reddit_url', sa.Text(), nullable=True),
    sa.Column('reddit_fetch_ok', sa.Boolean(), nullable=True),
    sa.Column('reddit_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reddit_comments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_approved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['reddit_queries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('query_id', 'url', name='uq_reddit_post_query_url')
    )
    op.create_index(op.f('ix_reddit_posts_id'), 'reddit_posts', ['id'], unique=False)
    op.create_index(op.f('ix_reddit_posts_query_id'), 'reddit_posts', ['query_id'], unique=False)
    op.create_index(op.f('ix_reddit_posts_url'), 'reddit_posts', ['url'], unique=False)
    op.create_table('reddit_query_contexts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query_id', sa.UUID(), nullable=False),
    sa.Column('user_query', sa.Text(), nullable=True),
    sa.Column('queries', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('nlp_anchors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('topic_boundary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('schema_hints', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['reddit_queries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reddit_query_contexts_id'), 'reddit_query_contexts', ['id'], unique=False)
    op.create_index(op.f('ix_reddit_query_contexts_query_id'), 'reddit_query_contexts', ['query_id'], unique=False)
    op.create_table('reddit_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query_id', sa.UUID(), nullable=False),
    sa.Column('search_query', sa.Text(), nullable=False),
    sa.Column('subreddit', sa.Text(), nullable=True),
    sa.Column('analyzed_at', sa.Text(), nullable=True),
    sa.Column('direct_answer', sa.Text(), nullable=True),
    sa.Column('executive_summary', sa.Text(), nullable=True),
    sa.Column('overall_sentiment', sa.Text(), nullable=True),
    sa.Column('total_signals', sa.Integer(), nullable=True),
    sa.Column('themes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('market_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actionable_next_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['reddit_queries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reddit_summaries_id'), 'reddit_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_reddit_summaries_query_id'), 'reddit_summaries', ['query_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reddit_summaries_query_id'), table_name='reddit_summaries')
    op.drop_index(op.f('ix_reddit_summaries_id'), table_name='reddit_summaries')
    op.drop_table('reddit_summaries')
    op.drop_index(op.f('ix_reddit_query_contexts_query_id'), table_name='reddit_query_contexts')
    op.drop_index(op.f('ix_reddit_query_contexts_id'), table_name='reddit_query_contexts')
    op.drop_table('reddit_query_contexts')
    op.drop_index(op.f('ix_reddit_posts_url'), table_name='reddit_posts')
    op.drop_index(op.f('ix_reddit_posts_query_id'), table_name='reddit_posts')
    op.drop_index(op.f('ix_reddit_posts_id'), table_name='reddit_posts')
    op.drop_table('reddit_posts')
    op.drop_index(op.f('ix_reddit_queries_user_id'), table_name='reddit_queries')
    op.drop_index(op.f('ix_reddit_queries_user_email'), table_name='reddit_queries')
    op.drop_index(op.f('ix_reddit_queries_status'), table_name='reddit_queries')
    op.drop_index(op.f('ix_reddit_queries_id'), table_name='reddit_queries')
    op.drop_table('reddit_queries')
    # ### end Alembic commands ###
