"""add validate query model

Revision ID: 689e76e581df
Revises: 074422fad875
Create Date: 2026-09-14 12:25:52.563737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '689e76e581df'
down_revision: Union[str, Sequence[str], None] = '074422fad875'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validate_queries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('industry', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('search_queries', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('runpod_job_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('failed_at_step', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('searched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validate_queries_id'), 'validate_queries', ['id'], unique=False)
    op.create_index(op.f('ix_validate_queries_industry'), 'validate_queries', ['industry'], unique=False)
    op.create_index(op.f('ix_validate_queries_stage'), 'validate_queries', ['stage'], unique=False)
    op.create_index(op.f('ix_validate_queries_status'), 'validate_queries', ['status'], unique=False)
    op.create_index(op.f('ix_validate_queries_user_email'), 'validate_queries', ['user_email'], unique=False)
    op.create_index(op.f('ix_validate_queries_user_id'), 'validate_queries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validate_queries_user_id'), table_name='validate_queries')
    op.drop_index(op.f('ix_validate_queries_user_email'), table_name='validate_queries')
    op.drop_index(op.f('ix_validate_queries_status'), table_name='validate_queries')
    op.drop_index(op.f('ix_validate_queries_stage'), table_name='validate_queries')
    op.drop_index(op.f('ix_validate_queries_industry'), table_name='validate_queries')
    op.drop_index(op.f('ix_validate_queries_id'), table_name='validate_queries')
    op.drop_table('validate_queries')
    # ### end Alembic commands ###
