"""add feedback table

Revision ID: 816b57b976ce
Revises: e029f625004e
Create Date: 2026-04-25 15:25:56.806172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '816b57b976ce'
down_revision: Union[str, Sequence[str], None] = 'e029f625004e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_id'), 'contact', ['id'], unique=False)
    op.add_column('feedback', sa.Column('score', sa.Integer(), nullable=False))
    op.add_column('feedback', sa.Column('selected_features', sa.ARRAY(sa.String()), nullable=False))
    op.add_column('feedback', sa.Column('comments', sa.Text(), nullable=True))
    op.drop_constraint(op.f('feedback_user_id_fkey'), 'feedback', type_='foreignkey')
    op.drop_column('feedback', 'phone')
    op.drop_column('feedback', 'user_id')
    op.drop_column('feedback', 'message')
    op.drop_column('feedback', 'full_name')
    op.drop_column('packages', 'is_free')
    op.drop_column('packages', 'package_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages', sa.Column('package_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('packages', sa.Column('is_free', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('feedback', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('feedback', sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('feedback', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('feedback', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('feedback_user_id_fkey'), 'feedback', 'users', ['user_id'], ['id'])
    op.drop_column('feedback', 'comments')
    op.drop_column('feedback', 'selected_features')
    op.drop_column('feedback', 'score')
    op.drop_index(op.f('ix_contact_id'), table_name='contact')
    op.drop_table('contact')
    # ### end Alembic commands ###
