"""added all sources field in validate idea

Revision ID: 81916a935a49
Revises: 98dc69a54d2a
Create Date: 2026-09-21 17:04:43.101297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81916a935a49'
down_revision: Union[str, Sequence[str], None] = '98dc69a54d2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('validate_score_summaries', sa.Column('all_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('validate_score_summaries', 'all_sources')
    # ### end Alembic commands ###
