"""updated the validate score summary mmodel

Revision ID: 98dc69a54d2a
Revises: 7d9d233988e9
Create Date: 2026-09-18 16:33:28.121002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98dc69a54d2a'
down_revision: Union[str, Sequence[str], None] = '7d9d233988e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('validate_score_summaries', sa.Column('executive_verdict', sa.Text(), nullable=True))
    op.add_column('validate_score_summaries', sa.Column('aggregate_score', sa.Integer(), nullable=True))
    op.add_column('validate_score_summaries', sa.Column('dimensional_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('validate_score_summaries', sa.Column('competitive_landscape', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('validate_score_summaries', sa.Column('critical_vulnerabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('validate_score_summaries', sa.Column('evidentiary_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('validate_score_summaries', 'search_query')
    op.drop_column('validate_score_summaries', 'analyzed_at')
    op.drop_column('validate_score_summaries', 'total_signals')
    op.drop_column('validate_score_summaries', 'executive_summary')
    op.drop_column('validate_score_summaries', 'quantitative_scores')
    op.drop_column('validate_score_summaries', 'overall_sentiment')
    op.drop_column('validate_score_summaries', 'direct_answer')
    op.drop_column('validate_score_summaries', 'defensibility_vectors')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('validate_score_summaries', sa.Column('defensibility_vectors', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('validate_score_summaries', sa.Column('direct_answer', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('validate_score_summaries', sa.Column('overall_sentiment', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('validate_score_summaries', sa.Column('quantitative_scores', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('validate_score_summaries', sa.Column('executive_summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('validate_score_summaries', sa.Column('total_signals', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('validate_score_summaries', sa.Column('analyzed_at', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('validate_score_summaries', sa.Column('search_query', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('validate_score_summaries', 'evidentiary_sources')
    op.drop_column('validate_score_summaries', 'critical_vulnerabilities')
    op.drop_column('validate_score_summaries', 'competitive_landscape')
    op.drop_column('validate_score_summaries', 'dimensional_scores')
    op.drop_column('validate_score_summaries', 'aggregate_score')
    op.drop_column('validate_score_summaries', 'executive_verdict')
    # ### end Alembic commands ###
