"""add validate summary source table

Revision ID: aae9c059beaf
Revises: 8da394b8061a
Create Date: 2026-10-05 16:00:16.731266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aae9c059beaf'
down_revision: Union[str, Sequence[str], None] = '8da394b8061a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validate_summary_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('scrape_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['validate_queries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('query_id', 'url', name='uq_validate_summary_source_query_url')
    )
    op.create_index(op.f('ix_validate_summary_sources_id'), 'validate_summary_sources', ['id'], unique=False)
    op.create_index(op.f('ix_validate_summary_sources_query_id'), 'validate_summary_sources', ['query_id'], unique=False)
    op.create_index(op.f('ix_validate_summary_sources_url'), 'validate_summary_sources', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validate_summary_sources_url'), table_name='validate_summary_sources')
    op.drop_index(op.f('ix_validate_summary_sources_query_id'), table_name='validate_summary_sources')
    op.drop_index(op.f('ix_validate_summary_sources_id'), table_name='validate_summary_sources')
    op.drop_table('validate_summary_sources')
    # ### end Alembic commands ###
