"""add playstore query and review table

Revision ID: ddba2af8d56d
Revises: a25948273089
Create Date: 2026-03-27 12:51:59.793237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ddba2af8d56d'
down_revision: Union[str, Sequence[str], None] = 'a25948273089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playstore_queries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.Text(), nullable=False),
    sa.Column('app_id', sa.Text(), nullable=False),
    sa.Column('app_name', sa.Text(), nullable=True),
    sa.Column('runpod_job_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('failed_at_step', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summarized_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playstore_queries_id'), 'playstore_queries', ['id'], unique=False)
    op.create_index(op.f('ix_playstore_queries_status'), 'playstore_queries', ['status'], unique=False)
    op.create_index(op.f('ix_playstore_queries_user_email'), 'playstore_queries', ['user_email'], unique=False)
    op.create_index(op.f('ix_playstore_queries_user_id'), 'playstore_queries', ['user_id'], unique=False)
    op.create_table('playstore_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query_id', sa.UUID(), nullable=False),
    sa.Column('app_id', sa.Text(), nullable=False),
    sa.Column('review_id', sa.String(length=255), nullable=True),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('thumbs_up', sa.Integer(), nullable=True),
    sa.Column('review_created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reply_content', sa.Text(), nullable=True),
    sa.Column('reply_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['playstore_queries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('query_id', 'review_id', name='uq_playstore_review_query_review')
    )
    op.create_index(op.f('ix_playstore_reviews_app_id'), 'playstore_reviews', ['app_id'], unique=False)
    op.create_index(op.f('ix_playstore_reviews_id'), 'playstore_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_playstore_reviews_query_id'), 'playstore_reviews', ['query_id'], unique=False)
    op.create_table('playstore_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query_id', sa.UUID(), nullable=False),
    sa.Column('app_id', sa.Text(), nullable=False),
    sa.Column('app_name', sa.Text(), nullable=True),
    sa.Column('analyzed_at', sa.Text(), nullable=True),
    sa.Column('direct_answer', sa.Text(), nullable=True),
    sa.Column('executive_summary', sa.Text(), nullable=True),
    sa.Column('overall_sentiment', sa.Text(), nullable=True),
    sa.Column('total_signals', sa.Integer(), nullable=True),
    sa.Column('average_rating', sa.Text(), nullable=True),
    sa.Column('themes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('market_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actionable_next_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rating_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['playstore_queries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playstore_summaries_id'), 'playstore_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_playstore_summaries_query_id'), 'playstore_summaries', ['query_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_playstore_summaries_query_id'), table_name='playstore_summaries')
    op.drop_index(op.f('ix_playstore_summaries_id'), table_name='playstore_summaries')
    op.drop_table('playstore_summaries')
    op.drop_index(op.f('ix_playstore_reviews_query_id'), table_name='playstore_reviews')
    op.drop_index(op.f('ix_playstore_reviews_id'), table_name='playstore_reviews')
    op.drop_index(op.f('ix_playstore_reviews_app_id'), table_name='playstore_reviews')
    op.drop_table('playstore_reviews')
    op.drop_index(op.f('ix_playstore_queries_user_id'), table_name='playstore_queries')
    op.drop_index(op.f('ix_playstore_queries_user_email'), table_name='playstore_queries')
    op.drop_index(op.f('ix_playstore_queries_status'), table_name='playstore_queries')
    op.drop_index(op.f('ix_playstore_queries_id'), table_name='playstore_queries')
    op.drop_table('playstore_queries')
    # ### end Alembic commands ###
